seppukudevelopment/seppuku

src/main/java/me/rigamortis/seppuku/impl/management/ModuleManager.java
src/main/java/me/rigamortis/seppuku/impl/module/movement/PullDownModule.java

Yes I made an epic hack which exploits JJ's stupid anti cheat he was stupid and doesnt check negative y velocity 🤦‍♂ 🤦‍♀ also works on 2b cause I mean if JJ is stupid is there even a word for hause ok thx pls merge

Add pulldown

---

src/main/java/me/rigamortis/seppuku/impl/module/misc/ChestAlertModule.java

This adds an option for the alert to be present in chat, in a notification or both.

ChestAlert notification mode setting

---

src/main/java/me/rigamortis/seppuku/impl/module/render/WallHackModule.java

Made an option for wallhack to show end crystals

Add Endcrystals to Wallhack

---

src/main/java/me/rigamortis/seppuku/impl/module/combat/NoCrystalModule.java

- Added option PlaceOnSneak
- Improved detection for if the player is moving, is now based on their speed
- Fixed module not placing supporting blocks
- Fixed module unnecessarily changing player's current hand
- Slightly simplified hasStack()
- Simplified place()
- Simplified and fixed valid() (Now uses isReplaceable() and checkNoEntityCollision())

Fixed various problems with NoCrystal

---

src/main/java/me/rigamortis/seppuku/impl/gui/hud/GuiHudEditor.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/PlayerPreviewComponent.java
src/main/java/me/rigamortis/seppuku/impl/management/HudManager.java
src/main/java/me/rigamortis/seppuku/impl/module/ui/HudEditorModule.java

Bonus features because Im kind:
- Allow pressing escape to exit hud editor
- Fix for the badly made chat toggle bypass
Thanks now please give me dev roles @Rigamortis

Create Player Preview Component

---

src/main/java/me/rigamortis/seppuku/impl/management/ModuleManager.java
src/main/java/me/rigamortis/seppuku/impl/module/misc/HotBarRefillModule.java

HotbarRefill automatically refills your hotbar from your inventory when one of the items in the hotbar is lower than its maximum stack.

Added HotBarRefillModule

---

src/main/java/me/rigamortis/seppuku/impl/module/movement/ElytraFlyModule.java

This was tested on 9b9t and it works without any problems.

Add control mode

---

src/main/java/me/rigamortis/seppuku/impl/management/ModuleManager.java
src/main/java/me/rigamortis/seppuku/impl/module/misc/QuickCraftModule.java

Added QuickCraft: automatically collects the result when crafting.

Added QuickCraft

---

src/main/java/me/rigamortis/seppuku/impl/module/movement/ScaffoldModule.java

[Scaffold] Shorten code

---

src/main/java/me/rigamortis/seppuku/impl/module/movement/ElytraFlyModule.java

NoHunger conflicts with elytrafly so it doesn't hurt to disable it and letting the user know about it.

[ElytraFly] Use built-in functions and disable nohunger module on toggle

---

src/main/java/me/rigamortis/seppuku/impl/command/RenameModuleCommand.java
src/main/java/me/rigamortis/seppuku/impl/config/ModuleConfig.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/ArrayListComponent.java
src/main/java/me/rigamortis/seppuku/impl/management/CommandManager.java
src/main/java/me/rigamortis/seppuku/impl/management/ModuleManager.java
src/main/java/me/rigamortis/seppuku/impl/module/movement/ElytraFlyModule.java
src/main/java/me/rigamortis/seppuku/impl/module/render/ArrayListModule.java
src/main/java/me/rigamortis/seppuku/impl/module/render/HudModule.java

-Added arraylist sorting (alphabet, length, unsorted)
-Added command to change a modules name

Render Changes

---

readme.md
src/main/java/me/rigamortis/seppuku/impl/module/combat/TotemNotifierModule.java
src/main/java/me/rigamortis/seppuku/impl/module/combat/VelocityModule.java

- Updated readme to english more
- Add missing null check to TotemNotifier
- Optimized velocity by not running getMinecraft so often, fixed #41.

Velocity + TotemNotifier fix, readme updates

---

src/main/java/me/rigamortis/seppuku/impl/management/ModuleManager.java
src/main/java/me/rigamortis/seppuku/impl/module/misc/MiddleClickPearlModule.java

Allows the player to middle click while pointing in mid-air to send a pearl.
Closes #44.

Add MiddleClickPearlModule

---

src/main/java/me/rigamortis/seppuku/impl/module/movement/ElytraFlyModule.java

Moving the code that implements control mode in ElytraFly to trigger on Move allows us to prevent the player from falling. Bypass mode was outdated and no longer used.

Elytrafly: Control mode prevents the player from slowly falling, remove bypass mode

---

src/main/java/me/rigamortis/seppuku/api/gui/hud/component/DraggableHudComponent.java
src/main/java/me/rigamortis/seppuku/impl/config/HudConfig.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/CoordsComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/DirectionComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/FpsComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/NetherCoordsComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/PacketTimeComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/PingComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/PlayerCountComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/SpeedComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/TotemCountComponent.java
src/main/java/me/rigamortis/seppuku/impl/gui/hud/component/TpsComponent.java

Middle clicking on a hud component will now toggle snapping, so it won't be pulled to an anchor.
Right clicking on the coords component brings up inline nether coords.
Slightly changed some components to look nicer.

Toggleable anchor/glue snapping and nicer looking hud components

---

src/main/java/me/rigamortis/seppuku/impl/module/movement/NoFallModule.java

Not sure why anyone would turn this off but just incase i made it toggleable
I don't really know how to code so if i did this in a retarded way i apologize lol

Added ElytraDisable option to NoFall

---

src/main/java/me/rigamortis/seppuku/impl/module/movement/ElytraFlyModule.java

old math wouldnt slow down xz speed when looking up or down

Fixed Look mode math

---

src/main/java/me/rigamortis/seppuku/impl/module/world/NukerModule.java
src/main/java/me/rigamortis/seppuku/impl/module/world/SpeedMineModule.java

Added break mode for nuker/speedmine as described in this issue:
https://github.com/seppukudevelopment/seppuku/issues/59
Video:
https://streamable.com/61f7p2

Added HAV0X Break

---

src/main/java/me/rigamortis/seppuku/impl/module/combat/BurrowModule.java

Added instant burrow
Added smart tp option for modes INSTA and TP (teleporting into a solid block makes burrow fail, this searches for air blocks above the player. Very reliable from my testing.)
Added more checks before starting burrow (already burrowed, another player in hole, etc)
Some other minor changes and options

Added InstaBurrow and smart TP option to improve reliability

---

.gitignore
src/main/java/me/rigamortis/seppuku/api/gui/hud/component/BlocksComponent.java

Lets you pick fluid blocks in the hud so that you can, for example, show lava when using the xray module. The implementation is a frankenstein of example code so let me know if i did something wrong

Add support for fluid blocks to BlocksComponent

---

src/main/java/me/rigamortis/seppuku/impl/command/LocateFeatureCommand.java
src/main/java/me/rigamortis/seppuku/impl/management/CommandManager.java

Basically, its /locate but client-side and lets you set the origin location (for checking the nearest structure). This way you can get stronghold locations without ender eyes, for example. Let me know if anything needs to be changed. I'm super tired right now but I'll check tomorrow

Add LocateFeature command

---

src/main/java/me/rigamortis/seppuku/impl/command/LocateFeatureCommand.java

There's a typo that I didn't notice on last commit

Fixed LocateFeature command usage

---

src/main/java/me/rigamortis/seppuku/api/util/RenderUtil.java
src/main/java/me/rigamortis/seppuku/impl/management/ModuleManager.java
src/main/java/me/rigamortis/seppuku/impl/module/render/MapBoundsModule.java

Adds module that shows map boarders like the builtin Minecraft chunk boarders feature.

Adds MapBoundsModule
